name: CI/CD for dockerised Flask app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Clean up conflicting files and cache
        run: |
          echo "Cleaning __pycache__ and any extra folders"
          find . -type d -name "__pycache__" -exec rm -r {} +
          find . -type f -name "*.pyc" -delete
          rm -rf Dockerimagehub-main  # Prevent duplicate folders from ZIPs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask pytest

      - name: Run tests
        run: pytest

  build-and-publish:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/flasktest-app:latest

      - name: Image digest
        run: echo ${{ steps.build-and-publish.outputs.digest }}
